# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/airnd',
                'doc_host': 'https://mshahoyi.github.io',
                'git_url': 'https://github.com/mshahoyi/airnd',
                'lib_path': 'airnd'},
  'syms': {'airnd.core': {'airnd.core.foo': ('core.html#foo', 'airnd/core.py')}}}
